# Generated by Django 5.0.6 on 2024-05-17 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysTasks',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('theme', models.TextField()),
                ('complexity', models.IntegerField(blank=True, null=True)),
                ('image', models.TextField()),
                ('answer', models.TextField()),
                ('author', models.TextField(blank=True, null=True)),
                ('trust', models.IntegerField(blank=True, null=True)),
                ('source', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PhysThemes',
            fields=[
                ('theme', models.TextField(primary_key=True, serialize=False)),
            ],
        ),
    ]
