# Generated by Django 5.0.6 on 2024-05-17 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_alter_phystasks_image_alter_phystasks_trust'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phystasks',
            name='complexity',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
