# Generated by Django 5.0.6 on 2024-05-17 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_alter_phystasks_answer_alter_phystasks_author_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phystasks',
            options={'ordering': ['trust', 'theme', 'name']},
        ),
        migrations.AddField(
            model_name='phystasks',
            name='answer_type',
            field=models.CharField(choices=[('int', 'целое'), ('float', 'с плавающей точкой'), ('str', 'текстовое')], default='str', max_length=10),
        ),
        migrations.AlterField(
            model_name='phystasks',
            name='description',
            field=models.TextField(help_text='Введите описание задачи...'),
        ),
    ]
