# Generated by Django 5.0.6 on 2024-05-19 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_alter_phystasks_options_phystasks_answer_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phystasks',
            name='source',
            field=models.TextField(default='db'),
        ),
        migrations.AlterField(
            model_name='phystasks',
            name='theme',
            field=models.ForeignKey(default='Undefined', on_delete=django.db.models.deletion.CASCADE, to='lessons.physthemes', to_field='theme'),
        ),
        migrations.AlterField(
            model_name='physthemes',
            name='theme',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
