# Generated by Django 5.0.6 on 2024-05-19 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0006_physthemes_theme_id_alter_phystasks_source_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='physthemes',
            options={'managed': False},
        ),
    ]
